steps:
  - id: Build image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--network=cloudbuild','-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.' ]

  - id: Push image
    name: 'gcr.io/cloud-builders/docker'
    waitFor:
      - Build image
    args: [ 'push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}' ]

  - id: Tag image
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor:
      - Push image
    args: ['container', 'images', 'add-tag', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}','gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${TAG_NAME}']

substitutions:
  _IMAGE_NAME: "tb-jenkins"
images: [
      'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
]
